### ISSUE TITLE
Make club images on the grid be the same size

### ISSUE THREAD

**Issue by matchaTiff** [matchaTiff/Rutgers-Esports#14]
Some club images are different sizes
![image](https://user-images.githubusercontent.com/26097257/107318438-c63e9580-6a6a-11eb-9f98-086ee93d5c6c.png)

**Comment by sriRacha21** [comment]
How should we solve this? Should we clip off the empty sides of the images so they scale properly?

**Comment by matchaTiff** [comment]
> How should we solve this? Should we clip off the empty sides of the images so they scale properly?

yes thats what I plan to do with the image files
